# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoltUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(max_length=175, unique=True, verbose_name='User Name')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Last Name')),
                ('wordpress_link', models.CharField(blank=True, max_length=255, verbose_name='Wordpress Link')),
                ('wordpress_id', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Wordpress User Name')),
                ('wordpress_pass', models.CharField(blank=True, max_length=255, verbose_name='Wordpress Password')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
