# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolt_user', '0002_auto_20160425_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boltuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='boltuser',
            name='email',
            field=models.EmailField(default='guest@bolttest.com', max_length=255, unique=True, verbose_name='Email Address'),
        ),
    ]
