# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolt_user', '0003_auto_20160425_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boltuser',
            name='wordpress_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Wordpress User Name'),
        ),
    ]
